//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetProjectM7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Age { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ImageUrl { get; set; }
    }
}
