//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetProjectM7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderId { get; set; }
        public int Id { get; set; }
        public string Categorys { get; set; }
        public decimal ProductQty { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal DueAmount { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    }
}
